language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=logAnalyze.core,logAnalyze.utils -m unittest
  - coverage report --fail-under=90

after_success:
  - coveralls
