language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source=core,utils -m unittest
  - coverage report --fail-under=90
